# Generated by Django 4.1.4 on 2023-02-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('islandschool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
    ]
